### ISSUE TITLE
[User Story] User- & Permission-Management

### ISSUE THREAD

**Issue by eteubert** [podlove/radiator#140]
**As a** network owner
**I want** to manage users and their permissions in my network

#### Acceptance Criteria

1. ~~Invite users to my network or any podcast / episode in my network.~~
2. See all users in my network and their permissions
3. Manage (add/remove) permissions for users in my network (except my own)

**Comment by monkeydom** [comment]
Do you think 1. is a reasonable acceptance criteria? I would like to postpone that as that implies some sort of storage of uncommited data (e.g. I invite you, so you get an account creation email that in turn remembers that you also would have been given access to certain things)

**Comment by eteubert** [comment]
No you're right, this can be moved to a separate story.
