### ISSUE TITLE
REST API: chapter import

### ISSUE THREAD

**Issue by eteubert** [podlove/radiator#167]
Import various chapter files to an audio.

**Comment by monkeydom** [comment]
As far as I understand, the request is also for a non-destructive API. E.g. just converting to our rest result format without adding it to a specific podcast. Don't know how to best put that in a rest api. Maybe under the prefix `preview`? or `convert`?

**Comment by eteubert** [comment]
Interesting, didn’t think about it that way. Makes me think of the common „dry“ param in CLIs. But „preview“ prefix might work better for a REST API.
