### ISSUE TITLE
Refactor User/Meta/People Architecture

### ISSUE THREAD

**Issue by eteubert** [podlove/radiator#200]
- kill 1:1 between `Person` and `User`
- keep only authentication related things in `User`
- for other account or user management related matters, keep metadata in a `UserMeta` table
- add 1:n between `User` and `Person` because a user can be represented in different ways by different instances of a `Person` -- for example across different networks or simply to express different personas in different podcasts / episodes (Eric the coffee nerd, Eric the Elixir guy, Eric the dad, ...)

**Comment by monkeydom** [comment]
Yeah. Maybe change `UserMeta` to `UserProfile`? but generally fits the bill for me.
