### ISSUE TITLE
Episode image upload does not work

### ISSUE THREAD

**Issue by eteubert** [podlove/radiator#232]

**Comment by monkeydom** [comment]
should be fixed with 7d333be3b0dfaba1507058f133b1a3bfc483131a

timing was wrong, aka arc didn't know the id of the audio to associate itself with on creation.

**Comment by monkeydom** [comment]
note that the phoenix api still doesnt work, but the rest api on audios works now. wondering if we should remove the image from the rest getter of the episode, to avoid confusion that it might be settable here.

**Comment by monkeydom** [comment]
all but phoenix ui works, closing.
