### ISSUE TITLE
[Admin Story] ENV for email_from_name and email_from_email

### ISSUE THREAD

**Issue by sreimers** [podlove/radiator#299]
**As an** Admin
**I want** to override `email_from_name` and `email_from_email` with
ENV variables. Otherwise mail servers with strict checks deny delivery.

Ref:
https://github.com/podlove/radiator/blob/develop/config/config.exs#L32-L33

**Comment by eteubert** [comment]
Those ENVs already exist, but in another file: https://github.com/podlove/radiator/blob/develop/config/releases.exs#L36

- `EMAIL_FROM_NAME`
- `EMAIL_FROM_ADDRESS`

`config.exs` and `prod.exs` contain _compiletime_ config while `releases.exs` contains `runtime` config, enabling use of env vars.
