### ISSUE TITLE
Handle stored blobs better, separate between public accessible content and "source" content.

### ISSUE THREAD

**Issue by monkeydom** [podlove/radiator#33]
Currently the upload to the S3 style storage just returns a URL that is in turn used in the metadata. We need a blob abstraction that we use instead, which e.g. has a notion of source, derived data, public urls, etc.

**Comment by eteubert** [comment]
Playing around with an idea, in a separate repo for now: https://github.com/podlove/radiator-media-sketch

**Comment by eteubert** [comment]
Current implementation is good enough for now. We can revisit this as required.
