### ISSUE TITLE
Bad signup form data still inserts a user dataset, causing for "Email has already been taken".

### ISSUE THREAD

**Issue by jeyemwey** [podlove/radiator#72]
This is a bug with the signup module where incorrect form data saves a dataset, resulting in "*Email has already been taken*".

Steps to reproduce:

<ol>
<li>Open `/signup` and type in bad form data (e.g. non-matching passwords or an empty username).</li>
<li>An exception page will show up. 

<details>
<summary>Exception from logs</summary>
<pre>
radiator_1  | [debug] QUERY OK source="networks" db=0.9ms queue=1.2ms
radiator_1  | SELECT n0."id", n0."image", n0."title", n0."slug", n0."inserted_at", n0."updated_at" FROM "networks" AS n0 LIMIT 1 []
radiator_1  | [info] Sent 404 in 869ms
radiator_1  | [debug] ** (Ecto.NoResultsError) expected at least one result but got none in query:
radiator_1  |
radiator_1  | from n0 in Radiator.Directory.Network,
radiator_1  |   limit: 1
radiator_1  |
radiator_1  |     (ecto) lib/ecto/repo/queryable.ex:76: Ecto.Repo.Queryable.one!/3
radiator_1  |     (radiator) lib/radiator_web/controllers/login_controller.ex:70: RadiatorWeb.LoginController.sign_in_valid_user/3
radiator_1  |     (radiator) lib/radiator_web/controllers/login_controller.ex:1: RadiatorWeb.LoginController.action/2
radiator_1  |     (radiator) lib/radiator_web/controllers/login_controller.ex:1: RadiatorWeb.LoginController.phoenix_controller_pipeline/2
radiator_1  |     (radiator) lib/radiator_web/endpoint.ex:1: RadiatorWeb.Endpoint.instrument/4
radiator_1  |     (phoenix) lib/phoenix/router.ex:275: Phoenix.Router.__call__/1
radiator_1  |     (radiator) lib/radiator_web/endpoint.ex:1: RadiatorWeb.Endpoint.plug_builder_call/2
radiator_1  |     (radiator) lib/plug/debugger.ex:122: RadiatorWeb.Endpoint."call (overridable 3)"/2
radiator_1  |     (radiator) lib/radiator_web/endpoint.ex:1: RadiatorWeb.Endpoint.call/2
radiator_1  |     (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:33: Phoenix.Endpoint.Cowboy2Handler.init/2radiator_1  |     (cowboy) /app/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
radiator_1  |     (cowboy) /app/deps/cowboy/src/cowboy_stream_h.erl:296: :cowboy_stream_h.execute/3
radiator_1  |     (cowboy) /app/deps/cowboy/src/cowboy_stream_h.erl:274: :cowboy_stream_h.request_process/3
radiator_1  |     (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
</pre>
</details></li>
<li>Open `/signup` again and try to signup with the same email address. Radiator will return an input validation message "*Email has already been taken*".</li>
</ol>

**Comment by eteubert** [comment]
can't reproduce
