### ISSUE TITLE
Add GraphQL mutation for user registration

### ISSUE THREAD

**Issue by eteubert** [podlove/radiator#75]
We have a mutation for login (`authenticatedSession`) but the initial user registration is missing.

**Comment by monkeydom** [comment]
Okay, lets put in the graphql stuff for signup. Proposing:

```graphql
mutation { signup(username: String!, email: !String, password: String! }: session
```

**Comment by eteubert** [comment]
Maybe a common prefix for all auth related mutations so they appear together in API discovery: userSignup, userPasswordReset, userVerifyEmail, ...

**Comment by monkeydom** [comment]
ah good point, will add that. btw: how does one do a graphQL endpoint that only triggers a side effect? e.g. userResendVerificationEmail ?

**Comment by eteubert** [comment]
Looks like you _need_ to have a return type/value. But you could make it a Boolean and return true. See for example https://stackoverflow.com/a/44773532

**Comment by monkeydom** [comment]
Okay, I'll add a `userResendVerificationEmail` then.
