### ISSUE TITLE
Importer must have a User Agent when accessing remote files

### ISSUE THREAD

**Issue by eteubert** [podlove/radiator#87]
Since it's downloading episodes and other files it should be something easily identifyable as a bot so tracking software can exclude it. I suggest including "bot" as it's often already filtered out by default.

Maybe "Podlove Radiator Import Bot"? Or something more creative? :)

**Comment by monkeydom** [comment]
Ah. The metalove metadata scraping identifies itself as 

```
defp headers do
  [{"User-Agent", "metalove/#{Metalove.version()}"}]
end
```

Maybe
`RadiatorImportBot/1.0 (https://github.com/podlove/radiator)`
?

**Comment by eteubert** [comment]
Ah that's good, I only saw the enclosure sideloader. I like your suggestion. Including the github reference seems like good practice.
